# Generated by Django 3.2.7 on 2021-10-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dipakdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'dipakdata',
            },
        ),
        migrations.CreateModel(
            name='dipdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'dipdata',
            },
        ),
        migrations.CreateModel(
            name='maheshdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'maheshdata',
            },
        ),
        migrations.CreateModel(
            name='saurabhdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'saurabhdata',
            },
        ),
        migrations.CreateModel(
            name='swatidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'swatidata',
            },
        ),
    ]
